version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
environment:
  NUGET_API_KEY:
    secure: XJbuh2QTiHomtsvMIgeGFc27VfdM69XKjjEEHOOcKAEELRvb2yZp5CwNcEgRoD7V
build_script:
- cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "AppVeyor"
test: off
