version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
environment:
  NUGET_API_KEY:
    secure: Hap3+kDvFoLeY5F/EFw6p51gFFITTORIY/xo1/M7GZdBrTn3vn+HN3yF9VAg+Spi
build_script:
- cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "appveyor"
test: off
